# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_auto_20170912_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=50)),
                ('reporting_clinician', models.CharField(max_length=50)),
                ('report_date', models.DateField()),
                ('body', models.TextField()),
                ('nhs_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
    ]
