# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20170912_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nhs_number',
            field=models.CharField(max_length=20),
        ),
    ]
