# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20170912_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='DOD_DOC',
            field=models.CharField(default=111, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(default='British', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='first_incident',
            field=models.CharField(default='27 Sep 2017', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital_number',
            field=models.CharField(default='S101010101', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='nhs_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
