# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20170927_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deceased',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
